---
# tasks file for role1
- name: debug message role 1
  debug: msg="role1"

- block:
  - name: debug message development_env
    debug: msg="グループ階層1 {{ grp1 }}"

  - name: debug message local_dev
    debug: msg="グループ階層2 {{ grp2 }}"

  - name: debug message host
    debug: msg="ホスト変数 {{ hst }}"

  tags: dev

- block:
  - name: debug message production_env
    debug: msg="グループ階層1 {{ grp1 }}"

  - name: debug message local_dev
    debug: msg="グループ階層2 {{ grp2 }}"

  - name: debug message host
    debug: msg="ホスト変数 {{ hst }}"

  tags: prd
